In [1]:
from regression import linearRegression
import pandas as pd;
import numpy as np;
import matplotlib.pyplot as plt
import math

ModuleNotFoundError: No module named 'numpy'

In [ ]:
data = pd.read_csv('GOOGL.csv',index_col='Date');
data.head()

Open       High        Low      Close  Adj Close    Volume
Date                                                                       
2004-08-19  50.050049  52.082081  48.028027  50.220219  50.220219  44659096
2004-08-20  50.555557  54.594597  50.300301  54.209209  54.209209  22834343
2004-08-23  55.430431  56.796799  54.579578  54.754753  54.754753  18256126
2004-08-24  55.675674  55.855858  51.836838  52.487488  52.487488  15247337
2004-08-25  52.532532  54.054054  51.991993  53.053055  53.053055   9188602

In [ ]:
data['hl_pct'] = (data['High']-data['Low'])/data['Low'] *100
data['oc_pct']= (data['Close']-data['Open'])/data['Open'] * 100

In [ ]:
data = data[['Close','hl_pct','oc_pct', 'Volume']]
data.head()

Close    hl_pct    oc_pct    Volume
Date                                               
2004-08-19  50.220219  8.441017  0.340000  44659096
2004-08-20  54.209209  8.537317  7.227004  22834343
2004-08-23  54.754753  4.062364 -1.218966  18256126
2004-08-24  52.487488  7.753212 -5.726354  15247337
2004-08-25  53.053055  3.966113  0.990858   9188602

In [ ]:
data['predict'] = data['Close'].shift(-math.ceil(0.001*len(data)))
data.head()

Close    hl_pct    oc_pct    Volume    predict
Date                                                          
2004-08-19  50.220219  8.441017  0.340000  44659096  54.009010
2004-08-20  54.209209  8.537317  7.227004  22834343  53.128128
2004-08-23  54.754753  4.062364 -1.218966  18256126  51.056057
2004-08-24  52.487488  7.753212 -5.726354  15247337  51.236237
2004-08-25  53.053055  3.966113  0.990858   9188602  50.175175

In [ ]:
data.dropna(inplace=True)
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

In [ ]:
X=np.array(data.drop(['predict'],1))
Y=np.array(data['predict'])
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.1)

/tmp/ipykernel_93416/695483746.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  X=np.array(data.drop(['predict'],1))


In [ ]:
predict = linearRegression()
predict.fit(x_train,y_train)

(1, 4) (1, 1) (3983, 4) (3983, 1)


In [ ]:
b = predict.predict(x_test)

In [ ]:
(b-y_test)[0:10]

array([-1.91323521e+01, -1.13053911e+02, -9.73158893e+00, -6.12191715e+01,
       -4.88570877e+00,  1.05550729e+01, -3.36333092e+00, -3.27895467e+01,
        1.04639571e+01, -1.04950288e-01])

In [ ]:
y_test[0:20]

array([ 171.831833, 2908.649902,  312.832825,  504.003998,  245.475479,
        679.47998 ,  233.48349 ,  243.543549,  433.143158,  545.200012,
       1113.75    ,  416.10611 ,  197.597595,  757.650024,  177.037033,
       1258.140015, 1211.      ,  216.716721,  303.048035, 1430.140015])

In [ ]:
len(x_test)

443

In [ ]:
predict.params

array([[ 1.00318036e+00,  7.43613670e-01, -8.18059588e-01,
        -1.48165329e-07]])

In [ ]:
x_train

array([[ 4.04299286e+02,  1.40865767e+00,  3.46583016e-01,
         3.67292300e+06],
       [ 8.95795820e+01,  1.27549909e+00,  5.67514179e-01,
         9.68031000e+06],
       [ 2.34758008e+03,  1.18050069e+00,  7.88708852e-02,
         9.34800000e+05],
       ...,
       [ 5.29199219e+02,  8.15347478e-01,  1.32423247e-02,
         2.26513300e+06],
       [ 2.67577576e+02,  3.14252581e+00,  2.31961917e+00,
         1.32361510e+07],
       [ 7.06890015e+02,  2.05535828e+00, -7.46971657e-01,
         2.32690000e+06]])